<a href="https://colab.research.google.com/github/Volks24/Pytorch_test/blob/main/Pytorch_test_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

Tensors

In [5]:
tensor = torch.rand(3, 4)
tensor

tensor([[0.6880, 0.2963, 0.6786, 0.5497],
        [0.4440, 0.1028, 0.4847, 0.1977],
        [0.6027, 0.9620, 0.6612, 0.9465]])

In [6]:
tensor_3d = torch.rand(2, 3, 4)
tensor_3d

tensor([[[0.0941, 0.1827, 0.8346, 0.9181],
         [0.5150, 0.4782, 0.3053, 0.0600],
         [0.9793, 0.2087, 0.9927, 0.7794]],

        [[0.5350, 0.5158, 0.3412, 0.7988],
         [0.7622, 0.8023, 0.7553, 0.4469],
         [0.0711, 0.2946, 0.4770, 0.5490]]])

In [7]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

reshape and view son sinmilares , basicmente re dimensionan


In [10]:
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
my_torch = my_torch.view(5, 2)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [12]:
tensor_a = torch.tensor([1, 2, 3, 4, 5])
tensor_b = torch.tensor([6, 7, 8, 9, 10])

In [13]:
#Suma
tensor_a + tensor_b


tensor([ 7,  9, 11, 13, 15])

In [15]:
torch.add(tensor_a, tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [16]:
tensor_a * tensor_b

tensor([ 6, 14, 24, 36, 50])